# Generated by Django 4.2 on 2023-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="body_style",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Sedan"),
                    (2, "SUV"),
                    (3, "Hatchback"),
                    (4, "Pickup"),
                    (5, "Van"),
                    (6, "Truck"),
                    (7, "Bus"),
                    (8, "Motorcycle"),
                    (9, "Tricycle"),
                    (10, "Bicycle"),
                    (11, "Other"),
                ],
                default=11,
            ),
        ),
    ]
